#!/usr/bin/env bash

if [[ -z "${1}" ]]; then
  echo "Usage: "
  echo "new-script <your script name>"
  exit 1
fi

script_name="${PROJECT_ROOT}/scripts/shared/${1}"

touch "${script_name}"
chmod +x "${script_name}"
printf "#!/usr/bin/env bash\n\n" >"${script_name}"
code "${script_name}"
